SHELL:=/bin/mksh
BINFILES:='\.(png|jpe?g|gif|deb|rpm|vpp|rtf)$$'

all:

AUTOLDR_DIRS+=	common
AUTOLDR_DIRS+=	www

DBC:=$(basename $(notdir $(wildcard dbconfig/install/*.in)))
ifneq (*,${DBC})
define dbsystem =
D$1_IN:=dbconfig/install/$1.in
D$1_OUT:=dbconfig/install/$1
D$1_UP:=$$(wildcard dbconfig/upgrade/$1/*)
$${D$1_OUT}: dbc-init $${D$1_IN}
	@for rev in $$$$(dbc_share=$$$$PWD; dbc_basepackage=../dbconfig; \
	    dbc_dbtype=$1; dbc_oldversion='0~~~~'; \
	    . /usr/share/dbconfig-common/dpkg/postinst; \
	    _dbc_find_upgrades); do \
		printf '%s\n' '' "-- revision $$$$rev" ''; \
		cat dbconfig/upgrade/$1/$$$$rev; \
	done | cat $${D$1_IN} - >$$@
endef

$(foreach db,${DBC},$(eval $(call dbsystem,${db})))
DBC_OUT=$(foreach db,${DBC},${D${db}_OUT})
CLEANFILES+=${DBC_OUT}

dbc-init:
	@mkdir -p data

dbc-done: ${DBC_OUT}
	@rmdir data 2>/dev/null
else
dbc-done:
	# no dbconfig-common files to frobnicate
endif

metacheck:
	@echo Checking that all files are in UTF-8
	find * -type f -print0 | grep -zEv ${BINFILES} | xargs -0 -- isutf8
	@echo Checking for CVS/git conflict markers
	find * -type f -print0 | grep -zEv ${BINFILES} | xargs -0r mksh -c \
	    'grep -El "^[<>=]{7}( |\$$)" "$$@"; test $$? -eq 1' \
	    hpw-metacheck-helper-cvs
	@echo Ensuring there is no whitespace or CR at end of lines
	find * -type f -print0 | grep -zEv ${BINFILES} | xargs -0r mksh -c \
	    'pcregrep -l $$'\''[\t\x0B-\x0D ]$$'\'' "$$@"; test $$? -eq 1' \
	    hpw-metacheck-helper-eol
	@echo Checking for empty lines or missing newline at EOF
	rv=0; find * -type f -print0 | grep -zEv ${BINFILES} |& \
	    while IFS= read -p -d '' -r name; do \
		if [[ -n "$$(tail -c -1 "$$name")" ]]; then \
			rv=1; \
			print -r -- "$$name: no newline at EOF"; \
		fi; \
		if [[ -s $$name && -z "$$(tail -n 1 "$$name")" ]]; then \
			rv=1; \
			print -r -- "$$name: empty line at EOF"; \
		fi; \
	done; exit $$rv
	@echo All done.

syntaxcheck:
	@echo Running syntax checks, please verify output manually.
	rv=0; find * -name '*.php' -print0 |& while IFS= read -p -d '' -r; do \
		php -l "$$REPLY" | grep -v '^No syntax errors detected in '; \
		(( PIPESTATUS[0] )) && rv=1; \
	done; exit $$rv
	@echo done.

syntaxcheck5:
	@echo Running syntax checks, please verify output manually.
	rv=0; find * -name '*.php' -print0 |& while IFS= read -p -d '' -r; do \
		php5 -l "$$REPLY" | grep -v '^No syntax errors detected in '; \
		(( PIPESTATUS[0] )) && rv=1; \
	done; exit $$rv
	@echo done.

syntaxcheck7:
	@echo Running syntax checks, please verify output manually.
	rv=0; find * -name '*.php' -print0 |& while IFS= read -p -d '' -r; do \
		php7.0 -l "$$REPLY" | grep -v '^No syntax errors detected in '; \
		(( PIPESTATUS[0] )) && rv=1; \
	done; exit $$rv
	@echo done.

CLEANFILES+=var/version.php var/version.php~ www/artifact-version
var/version.php: debian/changelog
	printf '%s\n' '<?php' '' \
	    '/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT! */' '' \
	    "define('HPW_VERSION', '$$(dpkg-parsechangelog -n1 | \
	    sed -n '/^Version: /s///p')');" >$@~
	php -l $@~
	echo 'Hello-PHP-World (hello-php-world)' $$(dpkg-parsechangelog -n1 | \
	    sed -n '/^Version: /s///p') >www/artifact-version
	mv -f $@~ $@

CLEANFILES+=var/autoldr.php var/autoldr.php~
var/autoldr.php:
	set -e; set -o pipefail; set -A dirs; ndirs=0; \
	    for dir in ${AUTOLDR_DIRS}; do \
		dirs[ndirs++]=$$PWD/$$dir; \
	    done; \
	    printf '%s\n' '}BEGIN' $$'\t___CLASSLIST___' '}END' | \
	    phpab -n --indent $$'\t' -b "$$PWD" -t php://stdin "$${dirs[@]}" | \
	    sed --posix -e '1,/^}BEGIN/d' -e '/^}END/,$$d' | \
	    printf '%s\n' '<''?php' '$$classlist = array(' "$$(cat)" ');' >$@~
	php -l $@~
	mv -f $@~ $@

all: metacheck syntaxcheck dbc-done var/autoldr.php var/version.php

clean:
	rm -f ${CLEANFILES}

.PHONY: all clean metacheck syntaxcheck syntaxcheck5 syntaxcheck7
.PHONY: dbc-init dbc-done
