#!/bin/sh

# work around sadt not honouring the latest DEP8
test -n "$AUTOPKGTEST_TMP" || AUTOPKGTEST_TMP=${ADTTMP:-$TMPDIR}

set -e
# just to be safe
test -n "$AUTOPKGTEST_TMP"

. ./HPWname.inc

# copy tests and link code to test as-installed
cp -r tests "$AUTOPKGTEST_TMP/"
cd "$AUTOPKGTEST_TMP"
ln -s /usr/share/$HPW_package/common common
ln -s /usr/share/$HPW_package/www www
ln -s /usr/share/dbconfig-common/data/$HPW_package dbconfig
ln -s /var/lib/$HPW_package var

# actually do run the tests
php tests/fakeunit.php
