#!/bin/sh
test -n "$AUTOPKGTEST_TMP" || AUTOPKGTEST_TMP=${ADTTMP:-$TMPDIR}
set -e
test -n "$AUTOPKGTEST_TMP"
cp -r tests "$AUTOPKGTEST_TMP/"
cd "$AUTOPKGTEST_TMP"
ln -s /usr/share/hello-php-world/common common
ln -s /usr/share/hello-php-world/www www
ln -s /usr/share/dbconfig-common/data/hello-php-world dbconfig
ln -s /var/lib/hello-php-world var
cd tests
exec phpunit .
