#!/bin/sh

set -e

# Initialise debconf
. /usr/share/debconf/confmodule
# Initialise dbconfig-common
dbc_generate_include_owner=root:www-data
dbc_generate_include_perms=0640
dbc_generate_include=php:/var/lib/hello-php-world/dbconfig.inc
dbc_pgsql_createdb_encoding=UTF8
dbc_authmethod_user=password
. /usr/share/dbconfig-common/dpkg/config.pgsql
dbc_go hello-php-world "$@"
