#!/bin/mksh

export LC_ALL=C
unset LANGUAGE

die() {
	print -ru2 -- "E: $*"
	exit 1
}

[[ $(realpath "$0") = "$(realpath debian/Undotïn)" ]] || \
    die called in wrong directory
(( USER_ID )) || die called as root

set -e
set -o pipefail
set -x
. ./HPWname.inc
set +ex

if [[ $1 = remove ]]; then
	alias do2=do2_remove
else
	alias do2=do2_generate
fi

if [[ $HPW_autoload = true ]]; then
	phpabcomma=phpab,
elif [[ $HPW_autoload = false ]]; then
	phpabcomma=
else
	die "invalid HPW_autoload: $HPW_autoload"
fi

set -A substs -- \
    -e "s@phpab,@${phpabcomma}g" \
    -e "s@HPW_package@${HPW_package}g"

rm -f debian/control

function nuke {
	local x

	rm -f -- "$@"
	for x in "$@"; do
		[[ ! -h $x && ! -e $x ]] || die "could not remove $x"
	done
}

function do1 {
	do2 "$1" "$1.in"
}

function do2_generate {
	nuke "$1~" "$1"
	sed "${substs[@]}" <"$2" >"$1~" || die "could not substitute from $2"
	mv "$1~" "$1" || die "could not rename to $1"
}

function do2_remove {
	nuke "$1~" "$1"
	if [[ $1 = .gitignore ]]; then
		git checkout -- "$1" || die "could not reset $1"
	fi
}

do1 .gitignore
do2 debian/apache2/${HPW_package}.conf debian/apache2/conf.in
do1 debian/source/lintian-overrides
do2 debian/${HPW_package}.config debian/HPW.config.in
do2 debian/${HPW_package}.install debian/HPW.install.in
do2 debian/${HPW_package}.links debian/HPW.links.in
do2 debian/${HPW_package}.lintian-overrides debian/HPW.lintian-overrides.in
do2 debian/${HPW_package}.postinst debian/HPW.postinst.in
do2 debian/${HPW_package}.postrm debian/HPW.postrm.in
do2 debian/${HPW_package}.prerm debian/HPW.prerm.in
# must be last
do1 debian/control
